// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDW31o93k7R_P_PidPAovTIG1zbly2rA',
    appId: '1:1092880751011:web:36fef84b956eaa7e73a216',
    messagingSenderId: '1092880751011',
    projectId: 'my-private-notes-svb',
    authDomain: 'my-private-notes-svb.firebaseapp.com',
    storageBucket: 'my-private-notes-svb.appspot.com',
    measurementId: 'G-3E2MM43LWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAMUrihFYgUP3J-ut1DtVKPcsb0ekgnE',
    appId: '1:1092880751011:android:f57a8b16ee51683273a216',
    messagingSenderId: '1092880751011',
    projectId: 'my-private-notes-svb',
    storageBucket: 'my-private-notes-svb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlU5T360lMtin101xXfS60RmOHWH16oZo',
    appId: '1:1092880751011:ios:84e873442c5abe0773a216',
    messagingSenderId: '1092880751011',
    projectId: 'my-private-notes-svb',
    storageBucket: 'my-private-notes-svb.appspot.com',
    iosClientId: '1092880751011-p1oiisp23ibvpj9ndcs900t372bikq7o.apps.googleusercontent.com',
    iosBundleId: 'me.svbogdan.myprivatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlU5T360lMtin101xXfS60RmOHWH16oZo',
    appId: '1:1092880751011:ios:84e873442c5abe0773a216',
    messagingSenderId: '1092880751011',
    projectId: 'my-private-notes-svb',
    storageBucket: 'my-private-notes-svb.appspot.com',
    iosClientId: '1092880751011-p1oiisp23ibvpj9ndcs900t372bikq7o.apps.googleusercontent.com',
    iosBundleId: 'me.svbogdan.myprivatenotes',
  );
}
